### ISSUE TITLE
wiki文档好像写的有问题

### ISSUE THREAD

**Issue by ted423** [transmission-web-control/transmission-web-control#103]
文档里的路径是 /usr/local/transmission/share/transmission/public_html
ubuntu里是/usr/share/transmission/public_html
因为写了两个transmission，感觉是不小心写错了？

**Comment by trim21** [comment]
https://github.com/transmission-web-control/transmission-web-control/issues/89

**Comment by ted423** [comment]
> #89

要不注明下系统？
因为我跑脚本的时候自动识别不到路径。需要手动指定。
大部分人下意识会直接复制命令过去跑

**Comment by trim21** [comment]
自动搜索路径好像有点问题，有时间的时候再改进下

**Comment by ted423** [comment]
好，辛苦了
