### ISSUE TITLE
替换Tracker功能无法使用

### ISSUE THREAD

**Issue by LeePhe** [transmission-web-control/transmission-web-control#105]
Transmssion 版本:4.0.3 (6b0e49bbb2)
Tr Web Control 版本: v1.6.30
浏览器名称及版本：Chrome 113.0.5672.127
问题描述: 替换Tracker功能无法使用，点击确定后并没有将目标tracker替换，无反应

**Comment by fcying** [comment]
最近想给chdbits 换tracker..碰到了同样的问题. 
是不支持新版本的tr吗?

**Comment by paysenyu** [comment]
我也是，没办法操作

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
