### ISSUE TITLE
提议：tracker替换功能是否考虑支持正则匹配和指定tracker服务器限速功能

### ISSUE THREAD

**Issue by dmdyxx** [transmission-web-control/transmission-web-control#106]
例：
^https://www.xxxxcom/announce.php?passkey=.*?$ 
替换为：
https://tracker.xxxxx、.com/announce.php?$1

tracker服务器限速功能：
手里站点多的情况下，可以指定限制一些分享率已经很高的站点tracker服务器的最高上传速度，把上行流量更好的跑给低分享率或新进的站点

**Comment by trim21** [comment]
transmission 4.0 有限速组功能，等有精力了支持一下吧

**Comment by dmdyxx** [comment]
> 传输 4.0 有限速组功能，等有精力了支持一下吧

感谢回复，因为tr4.0 手里有几个站点不支持，所以拖着一直没更新，这两天单独装个docker测试下

**Comment by trim21** [comment]
我的意思是transmission支持了但是这个Web ui还不支持…

**Comment by dmdy123** [comment]
> 我的意思是transmission支持了但是这个Web ui还不支持…

哦哦 了解   已经升级了tr4.0  后边会持续关注   感谢大佬无私付出
