### ISSUE TITLE
列表无法按服务器排序

### ISSUE THREAD

**Issue by jdjxk** [transmission-web-control/transmission-web-control#109]
- Transmssion 版本: Transmission: 3.00 (bb6b5a062e), RPC: 16
- Tr Web Control 版本: v1.6.30 Action #360 最新编译版本
- 浏览器名称及版本：Chromium 114
- 问题描述: 无法按 Tracker 服务器排序，点击表头服务器按钮，列表无变化

**Comment by trim21** [comment]
我没用过这个功能，这个功能的预期行为是怎样的...

**Comment by trim21** [comment]
比如bt种子有多个tracker的时候如何排序？

**Comment by jdjxk** [comment]
旧版WebUI点击服务器后，会按照Tracker地址排序（同一个地址会排在一起，且按字母顺序排列），现在点击后仍然是乱序，没有变化，如下图：
![微信截图_20230530165210](https://github.com/transmission-web-control/transmission-web-control/assets/46536339/394e8e94-9ddc-42b3-9975-970c4632a915)

**Comment by jdjxk** [comment]
很少用BT，印象中是取该种子的第一个Tracker，排序方式可以参照qB

**Comment by trim21** [comment]
Action #360 最新编译版本 是哪个版本？ pr https://github.com/transmission-web-control/transmission-web-control/pull/107 的？

**Comment by jdjxk** [comment]
对的

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
