### ISSUE TITLE
修改种子文件或目录名称功能失效

### ISSUE THREAD

**Issue by jdjxk** [transmission-web-control/transmission-web-control#110]
- Transmssion 版本: Transmission: 3.00 (bb6b5a062e), RPC: 16
- Tr Web Control 版本: v1.6.30 Action #360 最新编译版本
- 浏览器名称及版本：Chromium 114
- 问题描述: 修改种子文件或目录名称功能失效，弹窗内容空白，且无法修改文件名

![微信截图_20230530165037](https://github.com/transmission-web-control/transmission-web-control/assets/46536339/3cea8ee8-411a-4a9f-9385-700cbf75f2ee)

**Comment by trim21** [comment]
duplicated https://github.com/transmission-web-control/transmission-web-control/issues/94
