### ISSUE TITLE
无法打开，提示：409: Conflict

### ISSUE THREAD

**Issue by 1984admin** [transmission-web-control/transmission-web-control#112]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:transmission-daemon 3.00 (bb6b5a062e)
- Tr Web Control 版本:1.6.30
- 浏览器名称及版本：edge 114.0.1823.37
- 问题描述:
默认会打开：/transmission/web/
去掉web/后，提示如下：

409: Conflict
Your request had an invalid session-id header.
To fix this, follow these steps:
When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks.
X-Transmission-Session-Id:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

请问如何解决？

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by trim21** [comment]
为什么要去掉web/？ /transmission/web/ 不能显示网页吗？

**Comment by trim21** [comment]
请描述具体问题，是无法显示种子列表还是什么其他的问题。

**Comment by 1984admin** [comment]
> 为什么要去掉web/？ /transmission/web/ 不能显示网页吗？

/web/是transmission自动的ui啊。

**Comment by trim21** [comment]
预期是要安装到 `/transmission/web/` 的。
