### ISSUE TITLE
webui显示的百分比显示会不会有问题

### ISSUE THREAD

**Issue by ted423** [transmission-web-control/transmission-web-control#114]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本: 4.03
- Tr Web Control 版本: action
- 浏览器名称及版本：
- 问题描述:
![image](https://github.com/transmission-web-control/transmission-web-control/assets/7042766/584902ee-d992-410b-994a-7dfc0f6e3eee)
![image](https://github.com/transmission-web-control/transmission-web-control/assets/7042766/f886d693-28df-4e26-91e9-0fa492ea6dea)
上图是remote-gui的，下图是action的
是从0改文件夹和文件名进行的校验（辅种），第二个任务是我在校验原任务看看情况
---

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by ted423** [comment]
![image](https://github.com/transmission-web-control/transmission-web-control/assets/7042766/78455b23-47fc-40f3-a489-1729ddeaa3d1)

这是gui上的，因为gui上不之前有出现显示问题（不显示在校验的种子），我在怀疑，是不是只有remotegui的显示是对的

**Comment by ted423** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
xx@xx-All-Series:~$ apt list --installed |grep transmi

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

transmission-common/jammy,jammy,now 4.0.3-0build1~jammy all [已安装，自动]
transmission-gtk/jammy,now 4.0.3-0build1~jammy amd64 [已安装]
transmission/jammy,jammy,now 4.0.3-0build1~jammy all [已安装]


官方显示就有问题，我在怀疑他返回的值(?)是不是其实是错的

**Comment by trim21** [comment]
直接调用api看看返回结果呗

**Comment by ted423** [comment]
```
{
      "activityDate": 1681679836,
      "addedDate": 1681307060,
      "doneDate": 1681679836,
      "downloadDir": "/share/Aidol/AKB48",
      "downloadedEver": 191712919552,
      "error": 0,
      "errorString": "",
      "hashString": "8f69110612d6758a9cc32ebf30c268f6a721500c",
      "id": 1386,
      "isPrivate": true,
      "labels": [],
      "leftUntilDone": 0,
      "name": "[2014.06.04] AKB48 - Request Hour Setlist Best 200 2014 (200~101 Ver.)",
      "peersGettingFromUs": 0,
      "peersSendingToUs": 0,
      "percentDone": 1,
      "queuePosition": 1385,
      "rateDownload": 0,
      "rateUpload": 0,
      "recheckProgress": 0.7447,
      "status": 2,
      "totalSize": 191712919552,
      "trackerStats": [
        {
          "announce": "http://jpopsuki.eu:7531//announce",
          "announceState": 0,
          "downloadCount": 98,
          "hasAnnounced": true,
          "hasScraped": true,
          "host": "jpopsuki.eu:7531",
          "id": 1555,
          "isBackup": false,
          "lastAnnouncePeerCount": 0,
          "lastAnnounceResult": "成功",
          "lastAnnounceStartTime": 1686140852,
          "lastAnnounceSucceeded": true,
          "lastAnnounceTime": 1686140854,
          "lastAnnounceTimedOut": false,
          "lastScrapeResult": "无法连接到 Tracker",
          "lastScrapeStartTime": 1686139490,
          "lastScrapeSucceeded": true,
          "lastScrapeTime": 1686140854,
          "lastScrapeTimedOut": false,
          "leecherCount": 0,
          "nextAnnounceTime": 0,
          "nextScrapeTime": 1686142660,
          "scrape": "http://jpopsuki.eu:7531//scrape",
          "scrapeState": 1,
          "seederCount": 3,
          "sitename": "jpopsuki",
          "tier": 0
        }
      ],
      "uploadRatio": 0.0939,
      "uploadedEver": 17994707283
    },
```

**Comment by ted423** [comment]
弄错

**Comment by trim21** [comment]
可能remoteGui是用文件列表算出来的。

**Comment by ted423** [comment]
我猜也是，因为之前有人说过类似的问题，只不过没issue,所以也不知道啥情况

**Comment by ted423** [comment]
> 我猜也是，因为之前有人说过类似的问题，只不过没issue,所以也不知道啥情况

就是下了99%之后，删了重加变100%，然后无论怎么弄都是100%了

**Comment by trim21** [comment]
那是transmission自己的问题吧

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
