### ISSUE TITLE
建议：在网页title显示当前上传下载速度

### ISSUE THREAD

**Issue by tedzhu** [transmission-web-control/transmission-web-control#116]
建议在网页title显示当前上传下载速度，这样浏览器tab中会显示

其他一些下载器也有类似功能。例如qbittorrent:  View menu -> Speed in title bar

![image](https://github.com/transmission-web-control/transmission-web-control/assets/484992/20762cd9-c7c9-4dd6-86c1-bbfdec83a2c1)

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
