### ISSUE TITLE
左下角总上传速度一直为0

### ISSUE THREAD

**Issue by Mmx88** [transmission-web-control/transmission-web-control#123]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:4.0.3
- Tr Web Control 版本:1.6.30（另外个issue里发的改善流畅度那个版本）
- 浏览器名称及版本：chrome版本 114.0.5735.198（正式版本） (x86_64)版本 
- 问题描述:今天开通ipv6后，docker的网络bridge改host后，无法显示总上传速度，左下角总上传速度一直为0，之前一直正常
- 截图
- <img width="1258" alt="image" src="https://github.com/transmission-web-control/transmission-web-control/assets/32005586/b987a934-5afe-401b-afe3-0eee40f14f6a">

**Comment by trim21** [comment]
这个issue先关掉了，这个问题添加到pr的todo了

**Comment by Mmx88** [comment]
> 这个issue先关掉了，这个问题添加到pr的todo了

又我重启docker，之后丢那去做其他事没注意，现在又可以正常显示了
