### ISSUE TITLE
Deleted items not automatically removed from list even when auto-reload is enabled

### ISSUE THREAD

**Issue by eltiel** [transmission-web-control/transmission-web-control#125]
Please provide the following information.

- Transmission version: 4.0.3
- Tr Web Control version: 1.6.30
- Browser name & version：Tested with Firefox 114 and Vivaldi 6.1.3035.111
- Problem description:
Deleted items are not visually removed from the list automatically, even when auto-reload is enabled. I can confirm that auto-reload is working as I can see indicators e.g. download speed, progress, etc for other active downloads are changing. But deleted item will remain in the list until I force a browser refresh.

**Comment by trim21** [comment]
try 1.6.31

**Comment by eltiel** [comment]
> try 1.6.31

In my case, updating to 1.6.31 didn't work. Any way to troubleshoot this?

**Comment by trim21** [comment]
> > try 1.6.31
> 
> In my case, updating to 1.6.31 didn't work. Any way to troubleshoot this?

does refreshing(ctrl+R or F5) the website work?

**Comment by eltiel** [comment]
> > > try 1.6.31
> > 
> > 
> > In my case, updating to 1.6.31 didn't work. Any way to troubleshoot this?
> 
> does refreshing(ctrl+R or F5) the website work?

Yes, the behaviour is same as 1.6.30. Reload via browser using Ctrl+R or F5 works, but auto-reload or even manual reload _within_ Web Control does not work.

**Comment by eltiel** [comment]
A quick demo of what I'm experiencing: https://file.io/m9N86VFzJulD

**Comment by trim21** [comment]
you can just paste mp4 file in github issue

**Comment by trim21** [comment]
I may know the reason, I'll try to fix this.

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
