### ISSUE TITLE
点上方工具栏的删除图标无效

### ISSUE THREAD

**Issue by Mmx88** [transmission-web-control/transmission-web-control#126]
Transmssion 版本:4.0.3
Tr Web Control 版本:1.6.30（另外个issue里发的改善流畅度那个版本）
浏览器名称及版本：chrome版本 114.0.5735.198（正式版本） (x86_64)版本
问题描述:点上方工具栏的删除图标无效（触发条件未知）刷新网页也不起作用，但是可以用右键菜单删除，并且流畅没卡

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
