### ISSUE TITLE
Page does not refresh automatically when torrent is deleted

### ISSUE THREAD

**Issue by haeho7** [transmission-web-control/transmission-web-control#127]
- Transmssion version: linuxserver/transmission:4.0.3
- Tr Web Control version: v1.6.30
- Browser name & version：Google Chrome 114.0.5735.198 (x86_64)
- Problem description: When deleting seeds and files using the toolbar or right-click menu, the seed list does not trigger a refresh automatically. need to manually refresh the entire webpage.

```sh
docker run -d \
  --name=transmission \
  --network=host \
  --restart=unless-stopped \
  -e TZ=Asia/Shanghai \
  -e PUID=99 \
  -e PGID=100 \
  -e UMASK=022 \
  -e USER=example \
  -e PASS='example' \
  -e TRANSMISSION_WEB_HOME='/transmission-web-control/' \
  -e WHITELIST='127.0.0.1,192.168.1.*' \
  -e PEERPORT=51413 \
  linuxserver/transmission:4.0.3
```

download transmission-web-control:

```sh
docker exec -it transmission bash

curl -sSL https://github.com/transmission-web-control/transmission-web-control/releases/download/v1.6.30/dist.tar.gz | tar zxv -C /transmission-web-control --strip-components 2
```

![Xnip2023-07-14_00-46-22](https://github.com/transmission-web-control/transmission-web-control/assets/40952365/945353d3-4d48-4d6d-87c0-abfbafded5cb)

![Xnip2023-07-14_00-47-01](https://github.com/transmission-web-control/transmission-web-control/assets/40952365/edd92e60-554b-4286-976f-010be7414246)

**Comment by haeho7** [comment]
#125

**Comment by trim21** [comment]
duplicated https://github.com/transmission-web-control/transmission-web-control/issues/125

**Comment by trim21** [comment]
try 1.6.31

**Comment by haeho7** [comment]
> 尝试1.6.31

it works!
