### ISSUE TITLE
用户标签不可点击

### ISSUE THREAD

**Issue by smilodon** [transmission-web-control/transmission-web-control#128]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:4.5.3
- Tr Web Control 版本:1.6.30
- 浏览器名称及版本：Edge 114.0.1823.79 
- 问题描述: 用户标签不可点击

![2023-07-16 13 09 22](https://github.com/transmission-web-control/transmission-web-control/assets/1050407/947cfced-9d7e-4bce-b429-1f582ca91b5e)

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
