### ISSUE TITLE
UI not changing after running install.bash script on a fresh install of transmission in Debian 12?

### ISSUE THREAD

**Issue by JHBoricua** [transmission-web-control/transmission-web-control#131]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

Please provide the following information.

- Transmssion version: 3.00
- Tr Web Control version: 1.6.30
- Browser name & version：Firefox 115.0
- Problem description: UI not changing after running install.bash script inside tools folder on a fresh install of transmission in Debian 12. I see the tr-web-control folder inside /usr/share/transmission. When I previously used the original but now deprecated install script by ronggang the UI updated right after. Am I missing some additional step or something?

**Comment by trim21** [comment]
Can you paste logs here?

**Comment by JHBoricua** [comment]
I assume you mean the transmission logs? If so, there's nothing there that points me anywhere. Stopping and starting the transmission-daemon service had no effect.

`
Jul 17 20:32:16 torrent01 systemd[1]: transmission-daemon.service: Deactivated successfully.
Jul 17 20:32:16 torrent01 systemd[1]: Stopped transmission-daemon.service - Transmission BitTorrent Daemon.
Jul 17 20:41:15 torrent01 systemd[1]: Starting transmission-daemon.service - Transmission BitTorrent Daemon...
Jul 17 20:41:15 torrent01 systemd[1]: Started transmission-daemon.service - Transmission BitTorrent Daemon.
Jul 17 20:41:31 torrent01 systemd[1]: Stopping transmission-daemon.service - Transmission BitTorrent Daemon...
Jul 17 20:41:31 torrent01 transmission-daemon[1880]: Closing transmission session... done.
Jul 17 20:41:31 torrent01 systemd[1]: transmission-daemon.service: Deactivated successfully.
Jul 17 20:41:31 torrent01 systemd[1]: Stopped transmission-daemon.service - Transmission BitTorrent Daemon.
Jul 17 20:43:09 torrent01 systemd[1]: Starting transmission-daemon.service - Transmission BitTorrent Daemon...
Jul 17 20:43:10 torrent01 systemd[1]: Started transmission-daemon.service - Transmission BitTorrent Daemon.
`

**Comment by trim21** [comment]
logs of install script

**Comment by JHBoricua** [comment]
Where are those written to?

**Comment by trim21** [comment]
> Where are those written to?

the stdout stderr of running install.bash…

**Comment by JHBoricua** [comment]
Ok, purged transmission install and installed again clean. There's only the web folder inside /usr/share/transmission

```
linuxadmin@torrent01:~$ ls /usr/share/transmission/
web
```
Now running the install.bash script
```
linuxadmin@torrent01:~$ cd transmission-web-control/
linuxadmin@torrent01:~/transmission-web-control$ sudo bash tools/install.bash 
use latest version
transmission-web-control will be installed to /usr/share/transmission, please confirm it's correct. otherwise use '-o' to set target directory
press 'y' to continue
Are you sure? y
Using temp dir /tmp/tmp.GTqoQ7RfGd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1564k  100 1564k    0     0   811k      0  0:00:01  0:00:01 --:--:-- 5388k
```
This is how the folder /usr/share/transmission looks like after the script runs:
```
linuxadmin@torrent01:~/transmission-web-control$ ls /usr/share/transmission/
assets  favicon.ico  index.html  index.mobile.html  tr-web-control  web
```

**Comment by JHBoricua** [comment]
So I'm guessing in Debian install should default to /usr/share/transmission/web instead? Looking at the old script it seems that's were the files were being installed at.

**Comment by JHBoricua** [comment]
Yep. Ran the install script again with -o /usr/share/transmission/web and the gui updated correctly.

**Comment by trim21** [comment]
> So I'm guessing in Debian it should default to /usr/share/transmission/web instead? Looking at the old script it was appending web to the path were the files were being installed at.

Looks like this changed in different version, not sure why...
