### ISSUE TITLE
限制下载速度反而限制了上传速度

### ISSUE THREAD

**Issue by coracoo** [transmission-web-control/transmission-web-control#132]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本: Transmission: 4.0.3 (6b0e49bbb2), RPC: 17
- Tr Web Control 版本: Web Control: v1.6.3 --Web Control: v1.6.31
- 浏览器名称及版本：edge
- 问题描述:
    限制速度有问题，我限制的下载速度，结果上传速度被限制了。一开始以为是4.0的问题，后来重装两次以后还是问题依旧。最后发现关闭限制下载速度，上传速度就恢复了。是不是UI写反了？
---

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by trim21** [comment]
transmission的行为，跟ui五官

**Comment by trim21** [comment]
> transmission的行为，跟ui无关
