### ISSUE TITLE
index.original.html not present for original UI button.

### ISSUE THREAD

**Issue by sanello84** [transmission-web-control/transmission-web-control#143]
- Transmssion version: 4.0.3 (6b0e49bbb2), RPC: 17
- Tr Web Control version: v1.6.31
- Browser name & version：Firefox 115.0.3
- Problem description: index.original.html not present in project so the original UI button does not work. It looks like this may have been originally generated via the install script on the origin project. Was nice to have for a backup in case there was an issue with Tr Web.

**Comment by DuncanTheFox** [comment]
I have the same problem on Brave/Chrome.

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
