### ISSUE TITLE
Unraid Docker 内的安装方式

### ISSUE THREAD

**Issue by KZNS** [transmission-web-control/transmission-web-control#144]
在Unraid上，对于Docker镜像 linuxserver/transmission，transmission 4.0.3

安装目录：/config
然后设置TRANSMISSION_WEB_HOME为 /config

如果安装时遇到下载问题，可以手动下载 <https://github.com/transmission-web-control/transmission-web-control/releases/latest/download/dist.tar.gz> 到 /tmp/tr-web-ctl/vlatest/ 下，然后通过 -v latest 指定安装版本，脚本会直接获取本地已下载的文件

如果能支持一个选择本地文件的参数就更好了

**Comment by trim21** [comment]
可以用https_proxy环境变量设置代理

**Comment by FujiZ** [comment]
我给 linuxserver 提了一个 PR, 现在可以通过  DOCKER MODS 的方式使用 web ui 了：
https://github.com/linuxserver/docker-mods/tree/transmission-transmission-web-control

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
