### ISSUE TITLE
多选300个种子几乎卡死

### ISSUE THREAD

**Issue by paysenyu** [transmission-web-control/transmission-web-control#153]
![image](https://github.com/transmission-web-control/transmission-web-control/assets/51367628/676023e6-fb9c-4040-9ea4-c468616010e9)

你好,因为刚迁移完系统和硬盘,所以需要对种子进行重新校验,一次性勾选所有种子重新校验这个步骤就已经卡死了

几乎动弹不得.  unraid 的docker 安装的 tr4.0.4  然后ui 是从realase 手动下载放入webui 目录的

**Comment by xb615381** [comment]
而且默认会显示200个种子..改不了..

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
