### ISSUE TITLE
增加tracker的对话框界面异常

### ISSUE THREAD

**Issue by rocdeng** [transmission-web-control/transmission-web-control#157]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本: 4.0.4
- Tr Web Control 版本: 1.6.31
- 浏览器名称及版本：Edge 117.0
- 问题描述: 选中种子，点击“增加新的tracker”，弹出的对话框显示异常。如下图。

![QQ截图20231013085534](https://github.com/transmission-web-control/transmission-web-control/assets/413922/cce29207-d7ed-4db3-b3d6-4b22d60a5912)

![QQ截图20231013085511](https://github.com/transmission-web-control/transmission-web-control/assets/413922/320f7834-2335-48ae-bcf5-693dde9fd869)

---

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by cnwikee** [comment]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

Transmssion 版本: 4.0.4
Tr Web Control 版本: 1.6.31
浏览器名称及版本：Cent Browser 版本 5.0.1002.354（正式版本）and Microsoft Edge 版本 118.0.2088.57 (正式版本) (64 位)
问题描述:添加tracker服务器的窗口界面，无法正常显示
![277104940-d78cf36f-a19b-45ea-9a46-30557962ddab](https://github.com/transmission-web-control/transmission-web-control/assets/63179671/3f278079-93bb-45f0-8542-f14d6484115f)
![277104945-aa787614-7418-4c33-87a1-a841708b36d4](https://github.com/transmission-web-control/transmission-web-control/assets/63179671/b9d4e8c8-b608-42ed-8f08-c14bd4d6031f)

**Comment by rocdeng** [comment]
最新的也还是有这个问题，我装回老版本的包了
https://gitee.com/amos123/transmission-web-control-fixed

**Comment by vampirefu** [comment]
Transmssion 版本: 4.0.5
Tr Web Control 版本: 1.6.33
浏览器名称及版本：版本 121.0.2277.4 (正式版本) stable应用，dev频道 (64 位)
问题描述:添加tracker服务器的窗口界面，无法正常显示

**Comment by liwenliang926** [comment]
Transmssion 版本： 4.0.3
Tr Web Control 版本： 1.6.33
浏览器名称及版本：Microsoft Edge 版本 120.0.2210.91（正式版本） （64 位）
问题描述：添加tracker服务器的窗口界面，无法正常显示
![联想截图_20240107111428](https://github.com/transmission-web-control/transmission-web-control/assets/38349229/503a2adc-c017-4614-b719-f5563b83e4bf)

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
