### ISSUE TITLE
[Suggestion] Build for English too

### ISSUE THREAD

**Issue by Meister1977** [transmission-web-control/transmission-web-control#170]
Suggestion.

## For English User
I asked Home Assistant developer @alexbelgium to change the UI to your fork instead of the non-developed original.

https://github.com/alexbelgium/hassio-addons/issues/1098

The only problem we (he) saw, that your build defaults the language to Chinese.  

Would it be possible to do any of these possible solutions?
1.) build a non-chinese release too
2.) UI should not force the language at first load to Chinese if the language of the browser (in the http header) doesn't contain any Chinese languages? And of corse, if the [Accept-Language] contains any of the UI transaltion, I suggest to load that. My suggestion: if no already saved language in config/cookie, use the language of the browser if UI has transalation. If the language of the browser is not known, use English. (Or ask first time.)

**Comment by trim21** [comment]
this ui has built-in i18n support, so the releases are for multiple language including english, there is no need for to create an English build.

**Comment by Meister1977** [comment]
Ok, in this case the only problem is the default languge. I think, it would be better if it would based on browser settings instead of default to Chinese if earlier was not set in the settings.

**Comment by trim21** [comment]
> Ok, in this case the only problem is the default languge. I think, it would be better if it would based on browser settings instead of default to Chinese if earlier was not set in the settings.

defualt language is based on `navigator.language`, you can send a PR to fix this

https://github.com/transmission-web-control/transmission-web-control/blob/3fe97162694fad915ba385447769018590ec9fd7/src/lib/utils.ts#L51C23-L51C41

**Comment by trim21** [comment]
never mind, I'll fix this

**Comment by trim21** [comment]
can you use your browser's console and tell my what's your `navigator.language`?

**Comment by Meister1977** [comment]
For me it is "en-US". But as I know, there is an array too. navigator.languages. It contains
"en-US", "en", "hu" for me.
(I am Hungarian, but using English).

And I think, it can be empty, so please handle that too without exception.

And a very big thank you to fix this!

**Comment by alexbelgium** [comment]
Thanks very much for your work !

Works fine on my system, I now see it in english. Dear @Meister1977, please try restarting my addon with version `4.0.4-2` ; it will update transmission-web-control automatically at start and you should see v1.6.32 at bottom right.
