### ISSUE TITLE
Add torrent file on mobile UI

### ISSUE THREAD

**Issue by Choff3** [transmission-web-control/transmission-web-control#176]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:
- Tr Web Control 版本:
- 浏览器名称及版本：
- 问题描述:

---

## For English User

Please provide the following information.

- Transmssion version: 4.0.5
- Tr Web Control version: 1.6.33
- Browser name & version：Firefox 120.0.1
- Problem description: I would like to be able to add a torrent file from the mobile UI.

**Comment by PatrickDanino** [comment]
You should be able to do this today. It's the icon in the top right corner.

**Comment by Choff3** [comment]
Currently you can only add torrent links, **not torrent files**, using the mobile UI. 

![IMG_2986](https://github.com/transmission-web-control/transmission-web-control/assets/42592276/77b2a1bc-9ef4-496e-b0dc-2a08fa4ccbd6)
![IMG_2987](https://github.com/transmission-web-control/transmission-web-control/assets/42592276/8e62c10e-a360-4cb8-bfdb-7b5f6d979ff5)
