### ISSUE TITLE
Tracker-replace function has no effect

### ISSUE THREAD

**Issue by RudyBzhBzh** [transmission-web-control/transmission-web-control#178]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:
- Tr Web Control 版本: 
- 浏览器名称及版本：
- 问题描述:

---

## For English User

Please provide the following information.

- Transmssion version: 4.0.5
- Tr Web Control version: 1.6.33
- Browser name & version：Firefox 121
- Problem description: 

"Tracker-replace" function seems to have no effect. I used it some times without issues when I was on transmission 3 and ronggang tr-web-control version.
Should it be working ? 

Thanks

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
