### ISSUE TITLE
1.6.33随机端口输入框被禁用

### ISSUE THREAD

**Issue by 782042369** [transmission-web-control/transmission-web-control#180]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:Transmission: 4.0.4
- Tr Web Control 版本: v1.6.33
- 浏览器名称及版本：谷歌最新
- 问题描述: 随机端口设置被禁用了

---

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by 782042369** [comment]
![image](https://github.com/transmission-web-control/transmission-web-control/assets/28727900/07cc0c4a-66d8-4d67-8409-d003ced46f37)

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
