### ISSUE TITLE
Several Bugs

### ISSUE THREAD

**Issue by maxcom99** [transmission-web-control/transmission-web-control#190]
Please provide the following information.

Transmission: 4.0.5 (a6fe2a64aa), RPC: 17
Web Control: v1.6.33
Chrome latest
- Problem description:
First, thank you for continuing the work, by far my favorite UI.
A couple of issues
#-------- 01
The number of torrents per page is not saved and reverts to 30 on reload.
#-------- 02
Selecting a torrent, opening the file list and adding a filter like "*.jpg" - 2 issues:
-Hitting enter just removes the value
-Clicking the funnel/filter icon no longer does anything
#--------- 03
Selecting a torrent, right click, change download location. Making a change in the path and hitting enter deletes any changes to the path
#--------- 04
Sort downloading torrents by remaining time, upon auto reload, the list is no longer sorted

Thanks again!!

**Comment by maxcom99** [comment]
So... is this project dead?

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
