### ISSUE TITLE
删除种子后种子列表没有更新

### ISSUE THREAD

**Issue by initiali** [transmission-web-control/transmission-web-control#196]
- Transmssion 版本:4.0.5 (a6fe2a64aa)
- Tr Web Control 版本:v1.6.33
- 浏览器名称及版本：Firefox 122.0
- 问题描述:在种子列表里删除一个种子并同时删除文件后，后端文件已成功删除，但前端列表没有自动更新，点击刷新当前数据的按钮也不会更新列表，只能刷新整个页面才能更新。

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
