### ISSUE TITLE
Adding URL fails on Chrome using Mobile UI

### ISSUE THREAD

**Issue by PatrickDanino** [transmission-web-control/transmission-web-control#198]
## For English User

Please provide the following information.

- Transmssion version: 3
- Tr Web Control version:  v1.6.33
- Browser name & version：Chrome
- Problem description:

Adding a torrent using the URL and the Mobile UI often fails the first time. You have to do it again even though the dialog dismissed.

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
