### ISSUE TITLE
功能建议：希望能添加当日上传量，下载量等数据统计功能

### ISSUE THREAD

**Issue by myghid** [transmission-web-control/transmission-web-control#221]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本:4.0.5
- Tr Web Control 版本:latest
- 浏览器名称及版本：firefox
- 问题描述:

---功能建议：希望能添加今日上传量，下载量等数据统计功能

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
