### ISSUE TITLE
一键URL失效 "http://admin:admin@192.168.1.100:9091/"

### ISSUE THREAD

**Issue by kidzgy** [transmission-web-control/transmission-web-control#227]
- Transmssion 版本: 套件版4.0.5-26
- Tr Web Control 版本:1.6.33
- 浏览器名称及版本：Firefox123
- 问题描述:
假定NAS地址是 192.168.1.100，账号密码均是admin，tr端口默认9091。
如果要进入tr管理页面，则在浏览器输入 "http://192.168.1.100:9091" ，此时会弹出输入账号密码的对话框。
有一种方法，可以直接跳过账号密码，就是url里包含账号密码信息，比如 "http://admin:admin@192.168.1.100:9091" ，这样的话可以略过账号密码的对话窗口。
注意，在测试的时候，尽量先关闭浏览器而不是重启，因为关闭浏览器，会清空临时的cookies，而重启浏览器不会清空。

现在开始描述问题了，在首次运行浏览器后输入 "http://admin:admin@192.168.1.100:9091" ，会显示无法连接，等多久都不行，按F5刷新也不管用。如果以新标签方式打开 "http://192.168.1.100:9091" ，此时无需输入账号密码，可以直接正常连接。无需输入账号密码的原因是，此前输入的URL因为已经包含了账号密码信息，录入了cookies信息，所以再次打开就不用账号密码了。

注意，这个问题，无论是docker版还是套件版，使用了twc1.6.33均会复现该问题。而且docker版，哪怕不使用twc1.6.33，本身也会存也有这样的问题。

用回 github.com/ronggang/transmission-web-control 的1.6.1版本，无论是docker版还是套件版，均可以一键URL正常登录、浏览。

---

## For English User

TITLE：One-click URL invalidation "http://admin:admin@192.168.1.100:9091/"

- Transmssion version: Suite 4.0.5-26
- Tr Web Control version:1.6.33
- Browser name and version: Firefox123
- Problem Description.
Assuming NAS address is 192.168.1.100, account password is admin, tr port is 9091 by default.
If you want to enter the tr management page, then enter "http://192.168.1.100:9091" in the browser, and then a dialog box will pop up to enter the account password.
There is a way to skip the account password directly, that is, the url contains the account password information, such as "http://admin:admin@192.168.1.100:9091", in this case  directly skipped the account password input window.
Note that when testing, try to close the browser first instead of restarting it, because closing the browser will clear the temporary cookies, while restarting the browser will not clear them.

Now it's time to start describing the problem, after running the browser for the first time and typing in "http://admin:admin@192.168.1.100:9091", it will show that it can't connect, waiting as long as it takes, and pressing F5 to refresh doesn't work. If you open "http://192.168.1.100:9091" in a new tab, there is no need to enter the account password at this point, and you can connect directly and normally. The reason why you don't need to enter your password is that the URL you entered before already contains your password and cookies, so you don't need to enter your password again.

Note that this problem is reproduced with twc1.6.33, both in the docker version and the suite version. And the docker version, even without twc1.6.33, has this problem itself.

Using the 1.6.1 version of github.com/ronggang/transmission-web-control, both the docker version and the suite version can login and browse with one-click URL.

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
