### ISSUE TITLE
Transmission web control v.1.6.33 incorrectly shows time limits for alternate download/upload speeds in the "Alternative speeds" tab.

### ISSUE THREAD

**Issue by Seamas73** [transmission-web-control/transmission-web-control#228]
I use Transmission version: 2.84 in chroot space on my WD My Book Live and I also use Transmission 4.0.5 on my PC on Windows 10.
I installed Transmission Web Control v.1.6.33 on My Book Live (chroot space) following the instructions from this site, and added Transmission Web Control files to the folder c:\Program Files\Transmission\public_html\ on my PC.
I reduced download and upload speed of my Transmissions to 1024 kB/s from 7:00 to 22:30 for everyday. In transmission's settings.json on both devices "alt-speed-time-begin" parameter is set to 420, and "alt-speed-time-end" is set to 1350.
But when I open web-ui of both transmissions in any browser (I tried MS Edge, Opera and Firefox) I see in original web UI that Alternate speed uses from 7:00 till 22:30, and when I turn to Transmission Web Control UI and open transmission settings window I see in "Alternative speeds" tab that speeds limit lasts from 7:00 till 23:30.
![Opera Снимок_2024-04-06_170516_192 168 48 30](https://github.com/transmission-web-control/transmission-web-control/assets/36772070/355300f8-faa2-4960-a4c2-5af18f2095d9)
![Opera Снимок_2024-04-06_170430_192 168 48 30](https://github.com/transmission-web-control/transmission-web-control/assets/36772070/5c1d41eb-fe91-449b-b077-6a7026716190)

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
