### ISSUE TITLE
程序在1500种以后操作开始变卡

### ISSUE THREAD

**Issue by ted423** [transmission-web-control/transmission-web-control#66]
如果反馈 BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion 版本: Transmission: 4.0.3 (6b0e49bbb2)
- Tr Web Control 版本: 1.6.13
- 浏览器名称及版本： 112.0.5615.138
- 问题描述:
测试了下未重构的版本没这么卡，在极端情况下（过万种保种的用户）可能会遇到很大问题

---

## For English User

Please provide the following information.

- Transmssion version:
- Tr Web Control version:
- Browser name & version：
- Problem description:

**Comment by trim21** [comment]
性能问题暂时比较难搞，我还没看懂UI这部分是怎么写的

**Comment by trim21** [comment]
1.6.12 和 1.6.11 不卡吗？

**Comment by ted423** [comment]
1.6.12的时候还没添加到这么多种子

**Comment by ted423** [comment]
感觉不一定是webui这块

**Comment by ted423** [comment]
感觉是在批量暂停，开始，汇报之后会卡一长段时间，可能是tr正在执行导致的

**Comment by trim21** [comment]
tr的文件操作都是阻塞的

**Comment by ted423** [comment]
嗯，开始一个任务，之后几分钟可能就都卡着了。。。

**Comment by claresongs** [comment]
批量操作200个种子就好卡...

**Comment by trim21** [comment]
性能问题可能得要重写不少东西才能解决

**Comment by ted423** [comment]
最近感觉好多了

**Comment by claresongs** [comment]
真的好多了吗,真的超卡啊...现在同时选择200+的种子页面基本就进入假死状态了.
也不确定是不是tr4.0的问题,今天升级4.02后webui从1.61远古版更新到如今的1.63,选中的种子数量稍微多一点基本就瘫痪了

**Comment by ted423** [comment]
问题在于为啥你要同时选择200+种子.....
按我的理解，这要不卡，天理难容

**Comment by claresongs** [comment]
"你永远不知道用户怎么使用你的产品"
这操作之前是可以的...反正现在不敢轻举妄动了

**Comment by ted423** [comment]
> "你永远不知道用户怎么使用你的产品" 这操作之前是可以的...反正现在不敢轻举妄动了 其实不谈同时选中,现在就只要同时显示200个种子就已经瘫痪了

我这不会啊，不过我这是i7 4代...内存32G

**Comment by ted423** [comment]
不过我一般都不开自动刷新

**Comment by trim21** [comment]
调试了一下，是UI框架本身的问题 ...

**Comment by trim21** [comment]
确实是webui的问题

**Comment by byangmath** [comment]
> 确实是webui的问题

我近3000种子，打开后web后非常卡，点击某个种子要等很久才会有反应，退回 1.6.1 后好多了，希望早点修复这个问题呀

**Comment by ted423** [comment]
看来可能我已经卡习惯了。

**Comment by trim21** [comment]
差不多搞定了

试一下这个压缩包 https://github.com/transmission-web-control/transmission-web-control/actions/runs/5094486308

**Comment by trim21** [comment]
试了一下还有点bug，我再修一下（

**Comment by trim21** [comment]
方便的话手动安装这个版本试一下还卡不卡。

https://github.com/transmission-web-control/transmission-web-control/actions/runs/5096524174?pr=107

有部分功能还没完全实现，还有一些bug。

**Comment by claresongs** [comment]
同时操作1000个种子,丝滑流畅~坐等大佬后续更新

**Comment by byangmath** [comment]
大佬熬夜更新，现在丝般顺滑，而且比以前更好用了，可以shift键直接多选。期待大佬后续更新~

**Comment by ted423** [comment]
我弄了个最新的，似乎卡loading了.

**Comment by ted423** [comment]
弄错，看起来是不开自动刷新就会一直显示loading

**Comment by trim21** [comment]
发现有之前有的功能不能用了麻烦在pr或者这个issue里面反馈下

**Comment by byangmath** [comment]
- 最前面种子没有上传下载符号
- 种子、下载活跃数一打开的时候没有，过了一段时间才一个个陆续出现，但也很慢。一刷新，又不见了
- 服务器那一栏不显示，如第二条，但显示的是[object Object]
- 点击某条种子，下方当前种子属性中的服务器显示空白，文件也是显示空白

暂时发现这些问题

**Comment by ted423** [comment]
搜索似乎挂了

**Comment by claresongs** [comment]
添加种子时记忆的历史目录不见了
已经添加的种子没办法修改目录
只有鼠标左键可以选中种子,右键不行
没办法拖动鼠标复制名称和目录了
最上面那一排快捷按钮都不生效了,比如删除,重新校验,重新获取peer这些.
左下角状态栏是空白
还一个关于上面老哥的"种子、下载活跃数一打开的时候没有，过了一段时间才一个个陆续出现，但也很慢。一刷新，又不见了",在这个等待的过程中右键菜单栏没法取消
另外换肤功能也没了,虽然也没有几款皮肤就是了...

**Comment by trim21** [comment]
换肤功能删了，原本是的UI框架提供的，换了组件之后懒得支持好几个了

**Comment by claresongs** [comment]
好的好的 换肤本来也无关紧要,就是提一嘴

记得原来要操作某个种子只要直接右键单击就可以了,现在要先左键选中切换到想要操作的种子,然后才能右键,就多按了一下鼠标...

**Comment by trim21** [comment]
现在在没有选中种子的情况下直接右键倒是也可以直接操作被点击的那个种子

**Comment by claresongs** [comment]
> 

在已经选择一个种子的情况下右键其他种子,操作的对象还是之前那个种子,这时候右键就没有起到切换目标的功能

**Comment by trim21** [comment]
确实，待我抄一下QB的webui（

**Comment by zhichixiangsi** [comment]
新版本丝滑好多，种子前面的选项框好像没了

**Comment by trim21** [comment]
> 服务器那一栏不显示，如第二条，但显示的是[object Object]

@byangmath 给个截图

**Comment by byangmath** [comment]
> > 服务器那一栏不显示，如第二条，但显示的是[object Object]
> 
> @byangmath 给个截图

![image](https://github.com/transmission-web-control/transmission-web-control/assets/40292563/5936e3e0-6c09-4af7-b241-c63e2579686b)

**Comment by trim21** [comment]
修了部分问题

**Comment by byangmath** [comment]
感谢感谢。当前种子属性里面的服务器信息，有些种子需要点击两次才会出现tracker

**Comment by byangmath** [comment]
搜索栏没有用了，黄种啥的看不到警告/错误信息

**Comment by trim21** [comment]
原来现在回复更新也有通知了？

**Comment by byangmath** [comment]
可能没有，我新建了一个后发现太多条了就删了，更新了下之前的

**Comment by trim21** [comment]
![Uploading image.png…]()
我刚刚才受到通知

**Comment by byangmath** [comment]
还真可以

**Comment by ColderCoder** [comment]
总1.3k种，每页显示250种时，任何点击操作都会延迟1到4秒，卡顿甚至能影响浏览器切换tab，edge/firefox均如此

**Comment by yalidabuda** [comment]
目前做种数8000+，相对于3.0版本更卡，尤其在多选的时候会卡的时间更长

**Comment by lxnmail** [comment]
我用的群晖ds920. 种子添加的也不多140+个。也是非常的卡顿。

**Comment by ncxukc** [comment]
确实是webui导致的卡，群晖918+，Docker版TR4.0.3，种子数量300+，用1.6.31，每页显示50种以上卡得很，换回远古原版1.6.1就一切正常。

**Comment by mysll** [comment]
确实卡,一共才270个种,一页显示200个,就卡的不行,换回原版就不卡了

**Comment by trim21** [comment]
recommend https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG

推荐 https://github.com/openscopeproject/TrguiNG or https://github.com/jayzcoder/TrguiNG
