### ISSUE TITLE
状态始终显示连接服务器...

### ISSUE THREAD

**Issue by DDSDerek** [transmission-web-control/transmission-web-control#88]
- Transmssion 版本: 4.0.3
- Tr Web Control 版本: v1.6.18
- 浏览器名称及版本：chrome
- 问题描述: 状态始终显示连接服务器...

![image](https://user-images.githubusercontent.com/108336573/235335757-61899b23-179e-4f01-ab8b-633c2dc63e68.png)

经过测试 Tr Web Control v1.6.13 是正常连接的，后面的小版本没有测试。

**Comment by trim21** [comment]
截图一下控制台的请求？

**Comment by DDSDerek** [comment]
![image](https://user-images.githubusercontent.com/108336573/235336229-8db847c4-673b-4401-b600-bcc1bcd03273.png)

**Comment by DDSDerek** [comment]
![image](https://user-images.githubusercontent.com/108336573/235336236-1b9d9209-bafc-456a-a881-a2696df13b1e.png)

**Comment by trim21** [comment]
第一个请求409是预期行为。

控制台有报错吗？

**Comment by DDSDerek** [comment]
![image](https://user-images.githubusercontent.com/108336573/235336506-cd133ae2-4ed9-4457-876c-fa5c7ee64f36.png)

**Comment by trim21** [comment]
你把用户脚本都禁用了再试试...

**Comment by DDSDerek** [comment]
![image](https://user-images.githubusercontent.com/108336573/235336647-b861bf1f-39d1-4d52-be21-9355c06aa5b0.png)
换了FireFox，上面没有任何扩展和脚本，问题依旧

**Comment by trim21** [comment]
fixed in v1.6.22
