### ISSUE TITLE
TR4.0版本安装路径发生变化

### ISSUE THREAD

**Issue by Zayia** [transmission-web-control/transmission-web-control#89]
群晖下面安装，路径变更为/usr/local/transmission/share/transmission/public_html

**Comment by trim21** [comment]
用 `TRANSMISSION_WEB_HOME=/usr/local/transmission/share/transmission/public_html bash release/install-tr-control.sh` 命令进行安装

**Comment by trim21** [comment]
https://github.com/transmission-web-control/transmission-web-control/wiki/%E4%B8%AD%E6%96%87%E7%AE%80%E4%BB%8B

**Comment by Zayia** [comment]
> https://github.com/transmission-web-control/transmission-web-control/wiki/zh-CN

按照教程安装后，发现文件安装在了/usr/local/transmission/share/transmission/web

然而transmission对应的目录其实是/usr/local/transmission/share/transmission/public_html

所以并没有更新成功

还需要自己手动把web里面的文件迁移到public_html中

**Comment by 088** [comment]
在我的群晖7.1中，Transmission 4.0.3 的目录在这里：

/volume1/@appstore/transmission/share/transmission/public_html

**Comment by nickybaby57** [comment]
DSM7.2.1，Transmission 4.0.5  目录在这里
/var/packages/transmission/target/share/transmission/public_html/
